---
- hosts: all
  remote_user: "{{ login_user  }}"
  become: yes
  roles:
    - ansible-server-init


  vars_prompt:
    - name: "login_user"
      prompt: "Which user do you want to log in as?"
      default: "root"

    - name: "user"
      prompt: "What is the user name to create?"
      default: "deploy"

    - name: "password"
      prompt: "What is the user's password?"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7
